services:
  orders-db:
    container_name: postgres-orders
    image: postgres
    environment:
      - TZ=America/Recife
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=orders
    networks:
      - default

  orders:
    container_name: orders-container
    build:
      context: ./orders/
      dockerfile: Dockerfile
    environment:
      - TZ=America/Recife
    networks:
      - default
    ports:
      - 8081:8080
    depends_on:
      - orders-db

  stock-db:
    container_name: postgres-stock
    image: postgres
    environment:
      - TZ=America/Recife
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stock
    networks:
      - default

  stock:
    container_name: stock-container
    build:
      context: ./stock/
      dockerfile: Dockerfile
    environment:
      - TZ=America/Recife
    networks:
      - default
    ports:
      - 8082:8080
    depends_on:
      - stock-db

  api-gateway:
    container_name: krakend-container
    image: devopsfaith/krakend:2.9.1
    command: run -d -c /etc/krakend/krakend.json
    environment:
      - TZ=America/Recife
      - KRAKEND_PORT=8080
    ports:
      - 8080:8080
    networks:
      - default
    volumes:
      - ./krakend/krakend.json:/etc/krakend/krakend.json

networks:
  default:
    name: dev
    external: true